### ISSUE TITLE
'Login' doesn't work

### ISSUE THREAD

**Issue by StanKraftYT** [hymm/squid-tracks#213]
I've used squid tracks for months. After updating it today, I clicked 'Login', clicked on the 'Select this account', and it took me straight back to the page that says 'Login' and 'Login with Session Cookie'. Am I doing something wrong? Or is something broken?

**Comment by hymm** [comment]
One of the login API's is down (not nintendo's).  It'll probably be fixed in the next couple of days.

**Comment by littlepetfrog** [comment]
yea having the same issue 😭

**Comment by littlepetfrog** [comment]
Is the API still down? It's been quite a while now...

**Comment by StanKraftYT** [comment]
I’ve managed to log in perfectly using the ‘login with iksm cookie’ but this does mean i have to go through a long process of getting it every couple of days.

**Comment by StanKraftYT** [comment]
I’ve managed to log in perfectly using the ‘login with iksm cookie’ but this does mean i have to go through a long process of getting it every couple of days.

**Comment by TheVakman** [comment]
> 
> 
> One of the login API's is down (not nintendo's). It'll probably be fixed in the next couple of days.

Out of curiosity, which login API is down?

**Comment by TheVakman** [comment]
@hymm Which API is having the issue?

**Comment by kjhf** [comment]
Running squid tracks from Yarn seems to work and it will still publish to stat.ink. 
- Checkout the repo
- Install [npm](https://nodejs.org/en/) and [yarn](https://yarnpkg.com/getting-started/install/)
- Run with `yarn run dev` from the root squid-tracks directory.

**Comment by hymm** [comment]
I'm having trouble replicating this issue.  

- Do you see any errors in %AppData%/SquidTracks/log.log?
- Do you see any errors if you go to View->Toggle Developer Tools->Console?

**Comment by kjhf** [comment]
@hymm This is from a few days ago -- I am not experiencing the bug anymore.
This is from %AppData%\SquidTracks\logs\main.log, as the log.log doesn't have anything recent in it? Last time it was written was 2020-09-23.

```
[2020-10-19 22:22:21.427] [info] App starting...
[2020-10-19 22:22:21.551] [info] Checking for update
[2020-10-19 22:22:24.484] [info] Update for version 1.3.4 is not available (latest version: 1.3.4, downgrade is disallowed).
[2020-10-19 22:22:27.889] [info] SessionToken has probably expired, please login again
[2020-10-19 22:22:27.897] [info] TypeError: Cannot read property 'webApiServerCredential' of undefined
    at getApiLogin (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\splatnet2.js:199:22)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.getSessionWithSessionToken (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\splatnet2.js:310:26)
    at async checkStoredSessionToken (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\index.js:170:5)
    at async IpcMainImpl.<anonymous> (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\index.js:155:23)
[2020-10-19 22:22:28.119] [error] Error getting records: Error: Error requesting uri https://app.splatoon2.nintendo.net/api/records: StatusCodeError: 403 - {"message":"api_error_authentication_error","code":"AUTHENTICATION_ERROR"}
[2020-10-19 22:22:41.101] [error] Error Logging into Nintendo: TypeError: Cannot read property 'webApiServerCredential' of undefined
[2020-10-19 22:22:42.223] [info] SessionToken has probably expired, please login again
[2020-10-19 22:22:42.230] [info] TypeError: Cannot read property 'webApiServerCredential' of undefined
    at getApiLogin (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\splatnet2.js:199:22)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.getSessionWithSessionToken (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\splatnet2.js:310:26)
    at async checkStoredSessionToken (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\index.js:170:5)
    at async IpcMainImpl.<anonymous> (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\index.js:155:23)
[2020-10-19 22:22:42.711] [error] Error getting records: Error: Error requesting uri https://app.splatoon2.nintendo.net/api/records: StatusCodeError: 403 - {"code":"AUTHENTICATION_ERROR","message":"api_error_authentication_error"}
[2020-10-19 22:22:46.528] [info] SessionToken has probably expired, please login again
[2020-10-19 22:22:46.535] [info] TypeError: Cannot read property 'webApiServerCredential' of undefined
    at getApiLogin (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\splatnet2.js:199:22)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.getSessionWithSessionToken (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\splatnet2.js:310:26)
    at async checkStoredSessionToken (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\index.js:170:5)
    at async IpcMainImpl.<anonymous> (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\index.js:155:23)
[2020-10-19 22:22:46.763] [error] Error getting records: Error: Error requesting uri https://app.splatoon2.nintendo.net/api/records: StatusCodeError: 403 - {"message":"api_error_authentication_error","code":"AUTHENTICATION_ERROR"}
```

**Comment by kjhf** [comment]
Today:
```
[2020-10-31 00:33:33.939] [info] App starting...
[2020-10-31 00:33:34.341] [info] Checking for update
[2020-10-31 00:33:37.164] [info] Update for version 1.3.4 is not available (latest version: 1.3.4, downgrade is disallowed).
[2020-10-31 00:33:41.657] [info] SessionToken has probably expired, please login again
[2020-10-31 00:33:41.664] [info] TypeError: Cannot read property 'webApiServerCredential' of undefined
    at getApiLogin (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\splatnet2.js:199:22)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.getSessionWithSessionToken (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\splatnet2.js:310:26)
    at async checkStoredSessionToken (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\index.js:170:5)
    at async IpcMainImpl.<anonymous> (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\index.js:155:23)
[2020-10-31 00:33:42.155] [error] Error getting records: Error: Error requesting uri https://app.splatoon2.nintendo.net/api/records: StatusCodeError: 403 - {"message":"api_error_authentication_error","code":"AUTHENTICATION_ERROR"}
[2020-10-31 00:33:51.574] [error] Error Logging into Nintendo: TypeError: Cannot read property 'webApiServerCredential' of undefined
[2020-10-31 00:33:52.209] [info] SessionToken has probably expired, please login again
[2020-10-31 00:33:52.216] [info] TypeError: Cannot read property 'webApiServerCredential' of undefined
    at getApiLogin (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\splatnet2.js:199:22)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.getSessionWithSessionToken (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\splatnet2.js:310:26)
    at async checkStoredSessionToken (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\index.js:170:5)
    at async IpcMainImpl.<anonymous> (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\index.js:155:23)
[2020-10-31 00:33:52.436] [error] Error getting records: Error: Error requesting uri https://app.splatoon2.nintendo.net/api/records: StatusCodeError: 403 - {"code":"AUTHENTICATION_ERROR","message":"api_error_authentication_error"}
[2020-10-31 00:33:56.074] [info] SessionToken has probably expired, please login again
[2020-10-31 00:33:56.081] [info] Error: Error requesting uri https://api-lp1.znc.srv.nintendo.net/v1/Account/Login: RequestError: Error: Client network socket disconnected before secure TLS connection was established
    at requestWithErrorHandling (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\splatnet2.js:59:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async getApiLogin (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\splatnet2.js:175:16)
    at async Object.getSessionWithSessionToken (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\splatnet2.js:310:26)
    at async checkStoredSessionToken (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\index.js:170:5)
    at async IpcMainImpl.<anonymous> (C:\Users\User\AppData\Local\Programs\squid-tracks\resources\app.asar\build\main\index.js:155:23)
[2020-10-31 00:33:56.608] [error] Error getting records: Error: Error requesting uri https://app.splatoon2.nintendo.net/api/records: StatusCodeError: 403 - {"code":"AUTHENTICATION_ERROR","message":"api_error_authentication_error"}
```
